name: sortmatic_mobile
description: Aplicacion Movil Nativa SORT-MATIC - Asistente Virtual Generativo e Inspeccion de Planta

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Cliente HTTP REST y WebSockets
  http: ^1.2.1
  web_socket_channel: ^3.0.0
  flutter_secure_storage: ^9.0.0

  # Voz y Síntesis de Habla
  speech_to_text: ^7.2.0
  flutter_tts: ^4.0.2

  # UI Generativa & Gráficos
  flutter_markdown: ^0.7.1
  fl_chart: ^0.68.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
