# Generated by Django 5.0.14 on 2026-09-17 19:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_llenado_minimo', models.FloatField(default=60.0, help_text='Porcentaje minimo de llenado para aceptar una botella (0-100)')),
                ('umbral_certeza_ia', models.FloatField(default=80.0, help_text='Confianza minima del modelo YOLO para dar por buena una deteccion (0-100)')),
                ('velocidad_teorica', models.FloatField(default=40.0, help_text='Cadencia teorica de la faja, en botellas por minuto (BPM)')),
                ('botellas_por_lote', models.PositiveIntegerField(default=50, help_text='Tamano N de cada lote de produccion')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion de linea',
                'verbose_name_plural': 'Configuracion de linea',
            },
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('ACEPTADA', 'Aceptada'), ('DEFECTUOSA', 'Defectuosa'), ('LLENADO_BAJO', 'Llenado bajo')], max_length=15)),
                ('tipo_defecto', models.CharField(blank=True, choices=[('SIN_ETIQUETA', 'Sin etiqueta'), ('SIN_TAPA', 'Sin tapa'), ('OTRO', 'Otro')], max_length=15, null=True)),
                ('nivel_llenado_detectado', models.FloatField(blank=True, help_text='Porcentaje 0-100 estimado por geometria', null=True)),
                ('confianza_ia', models.FloatField(blank=True, help_text='Porcentaje 0-100', null=True)),
                ('estacion_descarte', models.CharField(blank=True, choices=[('ESTACION_1', 'Estacion 1 (defecto fisico)'), ('ESTACION_2', 'Estacion 2 (llenado bajo)')], max_length=12, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='LoteProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.CharField(editable=False, max_length=32, unique=True)),
                ('numero', models.PositiveIntegerField(editable=False, unique=True)),
                ('capacidad_lote', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=10)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='FotoDescarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='descartes/%Y/%m/%d/')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('inspeccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='linea.inspeccion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='loteproduccion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVO')), fields=('estado',), name='unico_lote_activo'),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecciones', to='linea.loteproduccion'),
        ),
        migrations.AddIndex(
            model_name='inspeccion',
            index=models.Index(fields=['lote', 'resultado'], name='linea_inspe_lote_id_acd1d8_idx'),
        ),
    ]
