# Generated by Django 5.0.14 on 2026-09-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComandoFaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('START', 'Start'), ('STOP', 'Stop'), ('RESET', 'Reset')], max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('consumido_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
    ]
