# Generated by Django 5.0.14 on 2026-09-19 07:00

import django.core.validators
import django.db.models.deletion
import linea.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linea', '0002_comandofaja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoFaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_marcha', models.BooleanField(default=False)),
                ('arduino_conectado', models.BooleanField(default=False)),
                ('ultimo_comando', models.CharField(blank=True, max_length=10)),
                ('detalle', models.CharField(blank=True, max_length=120)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de la faja',
                'verbose_name_plural': 'Estado de la faja',
            },
        ),
        migrations.RemoveField(
            model_name='configuracionlinea',
            name='umbral_certeza_ia',
        ),
        migrations.AddField(
            model_name='comandofaja',
            name='solicitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracionlinea',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracionlinea',
            name='confianza_defecto',
            field=models.FloatField(default=50.0, help_text='Certeza minima para marcar una botella como rota o sin tapa.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='configuracionlinea',
            name='confianza_deteccion',
            field=models.FloatField(default=25.0, help_text='Certeza minima para que el sistema considere que ve un objeto. Mas bajo = ve mas, con mas ruido.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='configuracionlinea',
            name='confianza_etiqueta',
            field=models.FloatField(default=80.0, help_text='Certeza minima para dar por presente la ETIQUETA. Mas alto = mas exigente.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='configuracionlinea',
            name='confianza_tapa',
            field=models.FloatField(default=65.0, help_text='Certeza minima para dar por presente la TAPA. Mas alto = mas exigente.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='configuracionlinea',
            name='dispositivo_inferencia',
            field=models.CharField(choices=[('cpu', 'CPU'), ('0', 'GPU (CUDA 0)')], default='cpu', help_text='Procesador que ejecuta el modelo de vision.', max_length=8),
        ),
        migrations.AddField(
            model_name='configuracionlinea',
            name='fraccion_cuello',
            field=models.FloatField(default=15.0, help_text='Altura del cuello mas la tapa como porcentaje de la botella. Calibra la medicion de llenado.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(50.0)]),
        ),
        migrations.AddField(
            model_name='configuracionlinea',
            name='tamano_imagen',
            field=models.PositiveIntegerField(choices=[(320, '320 px'), (416, '416 px'), (512, '512 px'), (640, '640 px'), (768, '768 px'), (960, '960 px'), (1280, '1280 px')], default=640, help_text='Resolucion a la que se analiza cada foto. Mas alta = mas precisa y mas lenta.'),
        ),
        migrations.AddField(
            model_name='configuracionlinea',
            name='version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='configuracionlinea',
            name='botellas_por_lote',
            field=models.PositiveIntegerField(default=50, help_text='Cuantas botellas entran en cada lote antes de abrir el siguiente.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='configuracionlinea',
            name='umbral_llenado_minimo',
            field=models.FloatField(default=60.0, help_text='Llenado minimo para aprobar una botella. Por debajo se descarta en la estacion 2.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='configuracionlinea',
            name='velocidad_teorica',
            field=models.FloatField(default=40.0, help_text='Cadencia teorica de la faja, en botellas por minuto (BPM).', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(600.0)]),
        ),
        migrations.AlterField(
            model_name='fotodescarte',
            name='imagen',
            field=models.ImageField(upload_to=linea.models.ruta_foto_descarte),
        ),
        migrations.AlterField(
            model_name='loteproduccion',
            name='capacidad_lote',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AddIndex(
            model_name='comandofaja',
            index=models.Index(fields=['consumido_en', 'creado_en'], name='linea_coman_consumi_e0e65d_idx'),
        ),
        migrations.AddIndex(
            model_name='inspeccion',
            index=models.Index(fields=['-fecha_hora', 'resultado'], name='linea_inspe_fecha_h_35fff4_idx'),
        ),
    ]
