# Generated by Django 5.0.14 on 2026-09-19 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador de sistemas'), ('SUPERVISOR', 'Supervisor de calidad'), ('OPERADOR', 'Operador de planta')], default='OPERADOR', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(blank=True, max_length=150)),
                ('accion', models.CharField(choices=[('INICIO_SESION', 'Inicio de sesion'), ('USUARIO_CREADO', 'Usuario creado'), ('USUARIO_ACTUALIZADO', 'Usuario actualizado'), ('USUARIO_ELIMINADO', 'Usuario eliminado'), ('CONFIG_ACTUALIZADA', 'Configuracion actualizada'), ('COMANDO_FAJA', 'Comando a la faja'), ('LOTE_ACTUALIZADO', 'Lote actualizado'), ('LOTE_CERRADO', 'Lote cerrado')], max_length=25)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Registros de auditoria',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['-creado_en'], name='cuentas_reg_creado__c2ee1e_idx'), models.Index(fields=['accion'], name='cuentas_reg_accion_a1deaf_idx')],
            },
        ),
    ]
